version: '3.7'

services:

  db:
    image: postgres:16-alpine
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - prod_db:/var/lib/postgresql/data

  #  app:
  #    build:
  #      context: .
  #    ports:
  #      - "8081:8081"
  #    depends_on:
  #      - account_db
  #    environment:
  #      GIN_MODE: release
  #      DB_SOURCE: postgresql://myuser:mypassword@account_db:5432/mydb?sslmode=disable
  #    command: sh /app/wait_for.sh db:5432 -- /app/start.sh


  gitlab:
    image: gitlab/gitlab-ee:16.10.1-ee.0
    container_name: gitlab
    hostname: gitlab.example.com
    environment:
      #     login: root
      GITLAB_ROOT_PASSWORD: "password"
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://gitlab.example.com'
    ports:
      - "8092:80"
      - "8022:22"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    # PERSONAL ACCESS TOKEN: glpat-BeSzNamz6hHGq7WpCuEU

  jenkins:
    hostname: jenkins.example.com
    container_name: jenkins
    build:
      context: .
      dockerfile: jenkins.Dockerfile
    ports:
      - '8091:8080'
    environment:
      #     login: user
      JENKINS_PASSWORD: "bitnami"
    volumes:
      - jenkins_data:/bitnami/jenkins

volumes:
  prod_db:
  jenkins_data: