version: '3.7'

services:
  db:
    image: postgres:16-alpine
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    networks:
      - test_riddle_network

  app_test:
    build:
      context: .
      dockerfile: test.Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      DB_SOURCE: postgresql://myuser:mypassword@db:5432/mydb?sslmode=disable
    command: sh wait_for.sh db:5432 -- /app/test.sh
    networks:
      - test_riddle_network

networks:
  test_riddle_network:
    driver: bridge
