// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package db

import (
	"encoding/json"
	"time"

	"github.com/sqlc-dev/pqtype"
)

type Solution struct {
	ID        int64                 `json:"id"`
	Condition json.RawMessage       `json:"condition"`
	Solution  pqtype.NullRawMessage `json:"solution"`
	CreatedAt time.Time             `json:"created_at"`
}

type User struct {
	ID             int64     `json:"id"`
	Email          string    `json:"email"`
	HashedPassword string    `json:"hashed_password"`
	CreatedAt      time.Time `json:"created_at"`
}
