// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: solution.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/sqlc-dev/pqtype"
)

const createSolution = `-- name: CreateSolution :one
INSERT INTO "solution" (condition, solution)
VALUES ($1, $2)
RETURNING id, condition, solution, created_at
`

type CreateSolutionParams struct {
	Condition json.RawMessage       `json:"condition"`
	Solution  pqtype.NullRawMessage `json:"solution"`
}

func (q *Queries) CreateSolution(ctx context.Context, arg CreateSolutionParams) (Solution, error) {
	row := q.db.QueryRowContext(ctx, createSolution, arg.Condition, arg.Solution)
	var i Solution
	err := row.Scan(
		&i.ID,
		&i.Condition,
		&i.Solution,
		&i.CreatedAt,
	)
	return i, err
}

const getSolution = `-- name: GetSolution :one
SELECT id, condition, solution, created_at FROM "solution"
where id = $1
LIMIT 1
`

func (q *Queries) GetSolution(ctx context.Context, id int64) (Solution, error) {
	row := q.db.QueryRowContext(ctx, getSolution, id)
	var i Solution
	err := row.Scan(
		&i.ID,
		&i.Condition,
		&i.Solution,
		&i.CreatedAt,
	)
	return i, err
}
